In [1]:
%load_ext autoreload
%autoreload 2

# Select 2023-2024 NBA Season

In [33]:
import pandas as pd

matchups = pd.read_csv("data/all_games.csv")
matchups

,Unnamed: 0,SEASON_ID,TEAM_ID_A,TEAM_ABBREVIATION_A,TEAM_NAME_A,GAME_ID,GAME_DATE,MATCHUP_A,WL_A,MIN_A,...,FT_PCT_B,OREB_B,DREB_B,REB_B,AST_B,STL_B,BLK_B,TOV_B,PF_B,PLUS_MINUS_B
0,7,22023,1610612737,ATL,Atlanta Hawks,22301159,2024-04-10,ATL vs. CHA,L,240,...,0.955,5.0,28.0,33.0,25,11.0,2,13,18,1.0
1,9,22023,1610612737,ATL,Atlanta Hawks,22301147,2024-04-09,ATL vs. MIA,L,292,...,0.714,5.0,41.0,46.0,29,8.0,3,18,16,6.0
2,15,22023,1610612737,ATL,Atlanta Hawks,22301104,2024-04-03,ATL vs. DET,W,240,...,0.810,8.0,29.0,37.0,24,14.0,3,10,13,-8.0
3,19,22023,1610612737,ATL,Atlanta Hawks,22301076,2024-03-30,ATL vs. MIL,L,239,...,0.800,6.0,34.0,40.0,27,7.0,5,10,18,9.0
4,21,22023,1610612737,ATL,Atlanta Hawks,22301060,2024-03-28,ATL vs. BOS,W,265,...,0.857,9.0,34.0,43.0,28,7.0,6,12,15,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52802,211440,21988,1610612766,CHH,Charlotte Hornets,28800140,1988-11-26,CHH vs. WAS,L,220,...,0.788,14.0,28.0,42.0,25,7.0,1,17,25,NaN
52803,211446,21988,1610612766,CHH,Charlotte Hornets,28800115,1988-11-22,CHH vs. DET,L,240,...,0.920,15.0,34.0,49.0,18,4.0,5,17,15,NaN
52804,211452,21988,1610612766,CHH,Charlotte Hornets,28800071,1988-11-15,CHH vs. NJN,L,240,...,0.519,16.0,30.0,46.0,22,9.0,5,19,24,NaN
52805,211458,21988,1610612766,CHH,Charlotte Hornets,28800024,1988-11-08,CHH vs. LAC,W,240,...,0.564,13.0,35.0,48.0,21,8.0,6,20,34,NaN
52806,211462,21988,1610612766,CHH,Charlotte Hornets,28800008,1988-11-04,CHH vs. CLE,L,240,...,0.706,14.0,40.0,54.0,33,16.0,3,20,24,NaN

In [56]:
season_2023 = matchups[matchups["SEASON_ID"] == 22023]

testing_results = season_2023.sample(1)

In [61]:
from api_helpers.three_step_pipeline import ThreeStepPipeline, Matchup_Regressor
import warnings 

warnings.filterwarnings('ignore')

print(testing_results.iterrows())

for i, matchup in testing_results.iterrows():
    matchup = matchup.to_frame().T
    matchup.drop("Unnamed: 0", axis=1, inplace=True)
    pipeline = ThreeStepPipeline(matchup=matchup)
    
    pipeline.make_prediction()

matchup["WL_A"]

<generator object DataFrame.iterrows at 0x738fc4b7c040>
Team_A_ID is 1610612743
Loaded model from disk
[[ 0.4975489   0.38323096 13.22127138 11.02069525 37.48961893 48.51031437
  30.03344761  0.43574874  0.33365919 15.36003564 10.2076357  30.82312865
  41.03076397 26.04613819]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

The outcome of this game is [[1. 1.]]

10498    W
Name: WL_A, dtype: object